### ISSUE TITLE
Update Node deps to next breaking release.

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-optparse#32]
**Is your change request related to a problem? Please describe.**

I'd like to update this library to use the newer Node deps that include breaking changes as it's currently blocking the same update for Spago: https://github.com/purescript/spago/pull/1129

**Describe the solution you'd like**

Update the Node deps.

**Additional context**
Add any other context about the change request here.

**Comment by f-f** [comment]
I think this is already fixed by #31? We could use that fork

**Comment by f-f** [comment]
Fixed in #31
