### ISSUE TITLE
Upload latest docs to Pursuit

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-optparse#7]
Latest docs on Pursuit are `v0.2.1`: https://pursuit.purescript.org/packages/purescript-optparse/

I'm not sure how much has changed since `v1.0.0`, but updating this would be helpful.

**Comment by safareli** [comment]
For tag v1.0.0 I got this error on travis https://travis-ci.org/f-o-a-m/purescript-optparse/builds/507800018#L1767 and docs were not published. once we make new release will make sure it's published.

**Comment by JordanMartinez** [comment]
Sounds good.

**Comment by safareli** [comment]
I'm still getting

`* ERROR: Your git working tree is dirty. Please commit or stash your changes first.`

but did manual publish 
https://pursuit.purescript.org/packages/purescript-optparse/2.0.0

**Comment by JordanMartinez** [comment]
Thanks! Not sure why you're getting that error...

**Comment by safareli** [comment]
it was because package-lock file was created after npm install

**Comment by JordanMartinez** [comment]
Ah...
